# Site settings
title: TheusZero - Blog
SEOTitle: TheusZero Blog
header-img: img/sideFondo.jpg
email: quetzal.noc@gmail.com
description: " Soy estudiante de la Universidad Tecnica Federico Santa Maria, de la carrera Ingenieria Civil en Telematica. Actualmente tengo 19 años y soy de Chile. Me gusta la Ciberseguridad y aprender, hago esta web como una forma de guardar cada comando y write up para asi poder tener un respaldo y leer el desarrollo de retos y maquinas de la plataforma HackTheBox "
keyword: "NOSE QUE ES"
url: "https://theuszer0.github.io"              # your host, for absolute URL
baseurl: "/TheusZero"                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     TheusZero
zhihu_username:     TheusZero
github_username:    TheusZer0
twitter_username:   TheusZero
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: TheusZero

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ingeniería Civil en Telemática - USM"
sidebar-avatar: images/me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "Sherry Wu",
        href: "https://xuechundesign.github.io"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "JiyinYiyong",
        href: "http://tiye.me/"
    },{
        title: "David's Game",
        href: "https://www.ruoyaowu.com/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    }
]
