# Site settings
title: TheusZero - Blog
SEOTitle: TheusZero Blog
header-img: images/sideFondo.jpg
email: quetzal.noc@gmail.com
description: "Soy estudiante de la Universidad Tecnica Federico Santa Maria, de la carrera Ingenieria Civil en Telematica. Actualmente tengo 19 años y soy de Chile. Me gusta la Ciberseguridad y aprender, hago esta web como una forma de guardar cada comando y write up para asi poder tener un respaldo y leer el desarrollo de retos y maquinas de la plataforma HackTheBox "
keyword: "HackTheBox, Hacking, Cybersecurity, USM, usm, Chile"
url: "https://theuszer0.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    TheusZer0
twitter_username:   TheusZero

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Netease settings
netease_comment: false

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Ingeniería Civil en Telemática - Cybersecurity Enthusiast - USM"
sidebar-avatar: https://theuszer0.github.io/images/me.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

disqus_username: theuszero

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "F4d3",
        href: "https://f4d3.io/"
    },{
    title: "dplastico",
    href: "https://dplastico.me/"
    },{
    title: "Binary Chaos",
    href: "https://hackingprofessional.github.io/Security/"
    },{
      title: "sckull",
      href: "https://sckull.github.io/"
    },
]
